let suggestions = [
    "Ghosts?",
    "Ghost device",
    "Are ghosts real scientifically?",
    "Are Ghosts real?",
    "Are ghosts good singers?",
    "Are ghosts good at academics?",
    "Are ghosts good?",
    "Are ghosts bad?",
    "Are ghosts killers?",
    "Are ghosts funny?",
    "Are ghosts good at maths?",
    "Are ghosts like human?",
    "Are ghosts like souls?",
    "Are ghosts deadly?",
    "Are ghosts fatal?",
    "Are ghosts friendly?",
    "Are ghosts good rappers?",
    "Can ghosts talk to us?",
    "Can we see ghosts through science?",
    "Can a ghost kill a person?",
    "Can I kill a ghost?",
    "Can I help a ghost?",
    "Can you tell whether a ghost has entered your home?",
    "Can you make a ghost device?",
    "Can ghosts do maths?",
    "Can ghosts study?",
    "Can we hear ghosts?",
    "Can ghosts kill us?",
    "Can ghosts hurt you?",
    "Can ghosts hurt you in sleep?",
    "Can ghosts die?",
    "Do ghosts age?",
    "Do ghosts exist?",
    "Do ghosts sleep?",
    "Do ghosts study?",
    "Do I look like a ghost?",
    "Do ghosts sees us?",
    "Do ghosts shout at us?",
    "Do ghosts code?",
    "Do ghosts bath?",
    "Do ghosts sing?",
    "Do ghosts eat?", 
    "Do ghosts drink?",
    "Do ghosts cut their nails?",
    "Do ghosts like being alone?",
    "Do ghosts like crowdy places?",
    "Has science approved presence of ghosts?",
    "How to see ghosts?",
    "How to know the presence of a ghost?",
    "How do I know if I'm a ghost?",
    "How do I contact ghosts?",
    "How do I help ghosts?",
    "How do I kill a ghost?",
    "How to make ghost checker device?",
    "How to talk to ghosts?",
    "How to check your home for any ghost?",
    "Is your home Haunted?",
    "I'm ghost?",
    "What is a ghost?",
    "What's a ghost?",
    "What do you mean by a ghost?",
    "Where are Ghosts?",
];
